apiVersion: v1
kind: Namespace
metadata:
  name: typesense
---
apiVersion: v1
kind: Service
metadata:
  name: ts
  namespace: typesense
  labels:
    app: typesense
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: typesense
  ports:
    - name: http
      port: 8108
      targetPort: 8108
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: typesense-config
#   namespace: typesense
# data:
#   TYPESENSE_ENABLE_CORS: "true"
# ---
apiVersion: v1
kind: Secret
metadata:
  name: typesense-secret
  namespace: typesense
data:
  TYPESENSE_API_KEY: YWJj # abc in base64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  namespace: typesense
  labels:
    service: typesense
    app: typesense
spec:
  serviceName: ts
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      service: typesense
      app: typesense
  template:
    metadata:
      labels:
        service: typesense
        app: typesense
    spec:
      serviceAccountName: typesense-service-account
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 300
      containers:
        - name: typesense
          envFrom:
            # - configMapRef: 
            #     name: typesense-config
            - secretRef:
                name: typesense-secret
          image: typesense/typesense:0.23.0.rc43
          command:
            - "/opt/typesense-server"
            - "-d"
            - "/usr/share/typesense/data"
            - "--api-port"
            - "8108"
            - "--peering-port"
            - "8107"
            - "--nodes"
            - "/usr/share/typesense/nodes"
          ports:
            - containerPort: 8108
              name: http
          resources:
            requests:
              memory: 100Mi
              cpu: "100m"
            limits:
              memory: 1Gi
              cpu: "1000m"
          volumeMounts:
            - name: nodeslist
              mountPath: /usr/share/typesense
            - name: data
              mountPath: /usr/share/typesense/data
        - name: typesense-node-resolver
          image: alasano/typesense-node-resolver
          command:
            - "/opt/tsns"
            - "-namespace=typesense"
          volumeMounts:
          - name: nodeslist
            mountPath: /usr/share/typesense
      volumes:
        - name: nodeslist
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: typesense-service-account
  namespace: typesense
# imagePullSecrets:
#  - name: your-image-pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: typesense
  name: typesense-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: typesense-role-binding
  namespace: typesense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: typesense-role
subjects:
- kind: ServiceAccount
  name: typesense-service-account
  namespace: typesense
